emit:
  - "@typespec/openapi3"  # Make sure the emitter is listed correctly ;-)

options:
  "@typespec/openapi3":
    output-file: ../../../dist/openapi.json  # Output file needs to be in dist directory alongside oas-to-zod.ts